# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 14:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(3)])),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(6)])),
                ('name', models.TextField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Department')),
            ],
        ),
    ]
